### ISSUE TITLE
Unable to upload to Dropbox; Error: Failed to establish a new connection

### ISSUE THREAD

**Issue by IoTmessenger** [d0ugal/hassio-dropbox-upload#7] opened 2018-09-06 09:56 UTC
Hi d0ugal,

Thanks for trying to fix our 'Intel NUC hassio-dropbox-sync issue' by informing us about your addon. I tried yours yesterday and again today. Having a problem though, it seems it does not want to connect to Dropbox API, see my Log beneath.

I am on the latest Hass.io 0.77.3 version. I have created a new Dropbox API app for testing your addon, but also tested using my existing one, which I now is working well.

I do not use SSL, have rebooted the system and even stopped my Pi-hole addon to rule out some DNS issue.
Any ideas or suggestions to try out?

Log
```
2018-09-06 11:32:58,048 - INFO - Starting Snapshot backup
2018-09-06 11:32:58,049 - INFO - Backing up 8 snapshots

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f2c47e6ff98>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /2/users/get_current_account (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2c47e6ff98>: Failed to establish a new connection: [Errno -3] Try again',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/upload.py", line 160, in <module>
    main()
  File "/upload.py", line 135, in main
    dbx.users_get_current_account()
  File "/usr/lib/python3.6/site-packages/dropbox/base.py", line 4245, in users_get_current_account
    None,
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 274, in request
    timeout=timeout)
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 365, in request_json_string_with_retry
    timeout=timeout)
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 449, in request_json_string
    timeout=timeout,
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /2/users/get_current_account (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2c47e6ff98>: Failed to establish a new connection: [Errno -3] Try again',))
```

**Comment by d0ugal** [comment] 2018-09-06 10:08
I suspect that you have a DNS issue. None of you addons will be able to connect to the internet if this is the case (if you try the Letsencrypt addon it will fail for the same reason). I also had this problem.

On your host machine you will want to set DNS for all docker containers. You will want to reboot the host after making this change (or maybe just restarting docker and the containers).

```
 /etc/docker/daemon.json
{
    "dns": ["10.0.0.2", "8.8.8.8"]
}
```

(I found the solution [here](https://www.reddit.com/r/homeassistant/comments/8vp9js/dns_if_you_are_running_hassio_using_docker_on/) - just to pass on the credit!)

Interestingly, maybe the original dropbox addon will work once you fix DNS. I only found and fixed the DNS issue after I gave up with that addon. I had a hack in this one for a while to make it work: https://github.com/d0ugal/hassio-dropbox-upload/commit/aa81b6e720af53862f4c6e42220df56934bad56e

**Comment by IoTmessenger** [comment] 2018-09-06 10:39
Thanks for pointing me in the right direction, I need to look a little deeper into this. Initially, I had to disable the systemd-resolved.service on Ubuntu server. This was needed to get the pi-hole addon to work on port 53 (as it was conflicting).
I will first try to get that service setup and use another dns_port for pi-hole addon, which is now possible in the newer versions.

In contrary to what the Reddit thread suggests, I can ping google.com OK when I ssh into Hass.io, so DNS itself is working.
However, I do not get any output when I use the 'nmcli dev show | grep 'IP4.DNS' command' to find the correct DNS address being used in my setup.
I will test some with the DNS settings for the Docker containers, need to find out the correct DNS IP used in my case first (probably not 10.0.0.2).

The original hassio-dropbox-sync addon could connect OK to the API itself, I believe there is some issue with the way the local paths are setup. When I run the underlying Dropbox_uploader.sh script the upload works correct.

**Comment by d0ugal** [comment] 2018-09-06 11:21
> The original hassio-dropbox-sync addon could connect OK to the API itself, I believe there is some issue with the way the local paths are setup. When I run the underlying Dropbox_uploader.sh script the upload works correct.

aha, I see. At least your log output showed that it found 8 snapshots. So hopefully you wont see that issue.

Let me know if you have any luck with the DNS problem. I can try reverting https://github.com/d0ugal/hassio-dropbox-upload/commit/aa81b6e720af53862f4c6e42220df56934bad56e so you can test it if you like. Or you can make the change manually too if you are happy poking around.

**Comment by IoTmessenger** [comment] 2018-09-06 11:25
I have been able to upload to Dropbox OK now, using your addon and suggestion. With a combination of setting the DNS port to 54 in Pi-hole, the starting of the systemd-resolved.service and adding DNS to the /etc/docker/daemon.json.
My DNS service in Pi-hole currently does not work anymore, but I know Frenck had some issues with this as well. Probably is with dnsmasq. But we know now what the underlying cause was, thanks again!

May I suggest it would be helpful to have your python script, while running, give some output in the Log? Until I checked my Dropbox itself, I was not able to tell if it was working or not. Refreshing the Log on your addon page was not updating anything. But at least I did not get any errors. so I assumed it must be doing something...
;)

**Comment by IoTmessenger** [comment] 2018-09-06 12:16
BTW, I do not get any output in the Log field, not even when the script has successfully finished. Maybe I need to refresh just before it turns the addon off again. Difficult to time that though.
;)

**Comment by iceman73** [comment] 2018-09-06 13:00
I also had this issue with your addon, but all others DNS is working. Once I added the  /etc/docker/daemon.json and restarted Docker, your addon started working for me. I am running on Ubuntu btw.

**Comment by IoTmessenger** [comment] 2018-09-06 13:22
@iceman73  Thanks for your update. Knowing that was enough for you, I disabled the systemd-resolved.service again and changed the DNS port for Pi-hole back to 53. DNS service is working again in Pi-hole and this addon also still works OK.
Probably should have tested adding DNS to the /etc/docker/daemon.json first, before breaking other stuff during the process...
😄

**Comment by d0ugal** [comment] 2018-09-06 14:09
> BTW, I do not get any output in the Log field, not even when the script has successfully finished. Maybe I need to refresh just before it turns the addon off again. Difficult to time that though.
;)

@IoTmessenger That is strange. I do see the logs. I actually spent a long time making the output useful. I have also been able to view it after the upload has finished and the container has stopped. It looks like this...

![2eefrepq](https://user-images.githubusercontent.com/48211/45162052-0851b600-b1e5-11e8-926e-524f7af45f9b.png)

**Comment by d0ugal** [comment] 2018-09-06 14:10
I'm tempted to reintroduce my DNS hack since that solved it for my addon. I don't understand why there would be DNS issues only for this container. I'll try and do some further investigation.

**Comment by IoTmessenger** [comment] 2018-09-06 14:16
Strange indeed, only when there is an error, it showed up in the Log. I did check in the python script, there are several LOG.info in it.
I will later try your addon on my DEV Hass.io server (running in a VM) as well, to see if there is the same issue.

**Comment by IoTmessenger** [comment] 2018-09-06 15:57
Just tested on my DEV server (still on version 0.75.3 Hass.io), also no Log info on the addon page (except when an error occurs).
Tried the addon page in another browser with the same issue.

@iceman73 Do you have Log info output on the addon page?

**Comment by nigel914** [comment] 2018-09-06 17:39
confirmed the uploads complete successfully. @IoTmessenger I didn't receive any logs during runtime I am currently running @d0ugal thanks for the good work looking forward to improvements.

Ubuntu 18.04.1 LTS on Intel NUC
Home Assistant 0.77.3

**Comment by IoTmessenger** [comment] 2018-09-07 07:16
@nigel914  Thanks for the info about the logging.
@d0ugal So there is something not working as designed for the log info, do you want me to raise a new issue for this?

**Comment by d0ugal** [comment] 2018-09-07 07:35
Yeah, please do open a logging issue. I guess we can close this one.

**Closed as completed by d0ugal** 2018-09-07 07:35 UTC
